name: "Publish Documentation to NIST Pages"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # - uses: martintb/Docs4NIST@themedir-bug
      - uses: usnistgov/Docs4NIST@0.7
        with:
          docs-folder: docs/
          formats: |-
            epub
            pdf
          pip-requirements: "requirements.txt"

